spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aipocket
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true